name: integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 9 * * *'

jobs:

  checks:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 6
      matrix:
        check: [rufflint, ruffformatcheck, doc8, docs, rstcheck, build-check]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox
      - name: Run checks with tox
        run: |
          tox -e ${{ matrix.check }}

  tests:
    needs: checks
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest]
        python-version: [3.8, 3.9, '3.10', 3.11, 3.12, 3.13]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install tox
        run: |
          pip install --upgrade pip
          pip install tox

      - name: Test with tox
        run: tox -e py
